fluentd:
  kind: 'StatefulSet'

  readinessProbe: {}

  livenessProbe: {}

  plugins:
    - fluent-plugin-opensearch --version 1.0.10

  fileConfigs:
    01_sources.conf: |-
      ## logs from podman
      <source>
        @type forward
        port 24232
      </source>

    02_filters.conf: |-

    03_dispatch.conf: |-

    04_outputs.conf: |-
      <match my.fluentd>
        @type opensearch
        @log_level debug
        host opensearch-cluster-master-0
        port 9200
      </match>

  replicaCount: 1

  dashboards:
      enabled: false

  service:
    type: "ClusterIP"
    annotations: {}
    # loadBalancerIP:
    # externalTrafficPolicy: Local
    ports:
    - containerPort: 24232
      protocol: TCP
      name: fluentd-dev
      
  podSecurityPolicy:
    enabled: false
    annotations: {}

  serviceAccount:
    create: true
    annotations: {}
    name: null

  volumes:
  - name: varlog
    persistentVolumeClaim:
      claimName: com-shr-apigee-fluentd-dev-varlog
  - name: varlibdockercontainers
    persistentVolumeClaim:
      claimName: com-shr-apigee-fluentd-dev-varlibdockercontainers
  - name: etcfluentd-main
    configMap:
      name: fluentd-main
      defaultMode: 0777
  - name: etcfluentd-config
    configMap:
      name: fluentd-config
      defaultMode: 0777

  volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcfluentd-main
    mountPath: /etc/fluent
  - name: etcfluentd-config
    mountPath: /etc/fluent/config.d/

  resources:
    limits:
        cpu: 1
        memory: 512Mi
    requests:
        cpu: 1
        memory: 512Mi
