fluentd:
  kind: 'StatefulSet'

  readinessProbe: {}

  livenessProbe: {}

  plugins:
    - fluent-plugin-opensearch --version 1.0.10

  fileConfigs:
    01_sources.conf: |-
      ## logs from podman
      <source>
        @type forward
        port 24232
      </source>

    02_filters.conf: |-

    03_dispatch.conf: |-

    04_outputs.conf: |-
      <match apigeedev>
        @type copy
        <store>
          @type opensearch
          logstash_format true  #인덱스 이름을 Date로 설정
          logstash_prefix apigee-dev-prv  #인덱스 이름 선행 접두사
          include_tag_key true
          <endpoint> 
            url https://vpc-awsdc-osc-com-shr-apigee-ayjq6sc35dqsokwhrexmlpbgkq.ap-northeast-2.es.amazonaws.com
            assume_role_arn arn:aws:iam::527449218003:role/apigee
            region ap-northeast-2
          </endpoint>
        </store>
        <store>
          @type opensearch
          logstash_format true #인덱스 이름을 Date로 설정
          logstash_prefix apigee-dev-pub #인덱스 이름 선행 접두사
          include_tag_key true 
          remove_keys requestPayload, responsePayload, userEmail  #입력 소스 Json 내 특정 키 값을 제거 하는 기능
          <endpoint>
            url https://vpc-awsdc-osc-com-shr-apigee-ayjq6sc35dqsokwhrexmlpbgkq.ap-northeast-2.es.amazonaws.com
            assume_role_arn arn:aws:iam::527449218003:role/apigee
            region ap-northeast-2
          </endpoint>
        </store>
        <store>
          type stdout
        </store>
      </match>

  replicaCount: 1

  dashboards:
      enabled: false

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: awsdc-nlb-com-shr-apigee-logdev
      service.beta.kubernetes.io/aws-load-balancer-type: 'external'
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: 'ip'
      service.beta.kubernetes.io/aws-load-balancer-scheme: 'internal'
      service.beta.kubernetes.io/aws-load-balancer-subnets: 'subnet-009b760ac175dc526, subnet-03064eeab3c6e8b02'
    type: "LoadBalancer"
    ports:
    - containerPort: 24232
      protocol: TCP
      name: fluentd-dev


  serviceAccount:
      annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::527449218003:role/eks-apigee-fluentd

  volumes:
  - name: varlog
    persistentVolumeClaim:
      claimName: com-shr-apigee-fluentd-dev-varlog
  - name: varlibdockercontainers
    persistentVolumeClaim:
      claimName: com-shr-apigee-fluentd-dev-varlibdockercontainers
  - name: etcfluentd-main
    configMap:
      name: fluentd-main
      defaultMode: 0777
  - name: etcfluentd-config
    configMap:
      name: fluentd-config
      defaultMode: 0777

  volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcfluentd-main
    mountPath: /etc/fluent
  - name: etcfluentd-config
    mountPath: /etc/fluent/config.d/

  resources:
    limits:
        cpu: 1
        memory: 2048Mi
    requests:
        cpu: 1
        memory: 2048Mi
