apiVersion: v1
kind: PersistentVolume
metadata:
  name: com-shr-apigee-fluentd-dev-varlog
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: com-shr-apigee-fluentd-dev-varlog
    namespace: opensearch
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: com-shr-apigee-fluentd-dev-varlibdockercontainers
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: com-shr-apigee-fluentd-dev-varlibdockercontainers
    namespace: opensearch
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: com-shr-apigee-fluentd-dev-varlog
  namespace: opensearch
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: com-shr-apigee-fluentd-dev-varlibdockercontainers
  namespace: opensearch
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
